# to ensure that plugin system is available
from ilastik.plugins import pluginManager

from objectClassificationWorkflow import ObjectClassificationWorkflow
from objectClassificationWorkflowBinary import ObjectClassificationWorkflowBinary
from objectClassificationWorkflowPrediction import ObjectClassificationWorkflowPrediction