image: Visual Studio 2017

clone_folder: c:\projects\ilastik

environment:
  ENV_NAME: test-env
  # set miniconda version explicitly
  MINICONDA: C:\Miniconda37-x64
  IlASTIK_ROOT: C:\ilastik
  VOLUMINA_SHOW_3D_WIDGET: 0
  APPVEYOR_CACHE_ENTRY_ZIP_ARGS: -xr!*/ -ir-!*.tar.bz2 -ir-!*.conda  # Exclude directories only cache downloaded tars

cache:
  - C:\Miniconda37-x64\pkgs -> appveyor.yml

install:
  - cmd: set "PATH=%MINICONDA%;%MINICONDA%\Scripts;%MINICONDA%\Library\bin;%PATH%
  - cmd: where conda
  - cmd: conda config --set always_yes yes --set changeps1 no --set channel_priority strict
  - cmd: conda update -q conda
  - cmd: conda install -c conda-forge conda-build
  # Get the current main of all submodules
  - cmd: git clone https://github.com/ilastik/ilastik-meta %IlASTIK_ROOT%\ilastik-meta
  - cmd: cd %IlASTIK_ROOT%\ilastik-meta
  - cmd: git submodule update --init --recursive
  - cmd: git submodule foreach "git checkout main"
  - ps: rm -Force -Recurse $env:IlASTIK_ROOT\ilastik-meta\ilastik\
  # replace with whatever version of ilastik triggered the appveyor
  - ps: cp -recurse C:\projects\ilastik $env:IlASTIK_ROOT\ilastik-meta\ilastik
  # Point to the current ilastik-meta
  - python ilastik/scripts/devenv.py create --name %ENV_NAME%
  - conda clean -p

build: off

test_script:
  - cmd: set PATH=%MINICONDA%;%MINICONDA%\Scripts;%MINICONDA%\Library\bin;%PATH%
  - cmd: CALL activate %ENV_NAME%
  - cmd: cd %IlASTIK_ROOT%\ilastik-meta\ilastik
  - cmd: set VOLUMINA_SHOW_3D_WIDGET=0
  - cmd: pytest --run-legacy-gui

# on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/main/scripts/enable-rdp.ps1'))
