channels:
  - ilastik-forge
  - conda-forge
  - nodefaults
dependencies:
  - python 3.7.*
  - numpy 1.21.*
  - appdirs
  - cachetools
  - dpct
  - fastfilters
  - future
  - greenlet
  - grpcio
  - h5py
  - hytra
  - ilastik-feature-selection
  - ilastikrag
  - ilastiktools
  - jsonschema
  - mamutexport
  - marching_cubes
  - ndstructs
  - nifty
  - psutil
  - pyopengl
  - pyqt 5.12.*
  - pyqtgraph
  - python-elf
  - pytiff
  - qimage2ndarray
  - scikit-image
  - scikit-learn
  # see note in conda recipe about tifffile compatibility
  - tifffile 2021.11.2
  # build 1.11.1=*_1028 on cf is the first to be compatible with numpy>1.19
  # need to bump this manually until there is a true version bump in vigra
  - vigra 1.11.1=*_1032
  - wsdt
  - xarray
  - z5py

  # Neural Network Workflow dependencies
  # can be changed to request gpu versions
  # Note that if you want packages from pytorch channel, it should be `pytorch` and `cpuonly`
  # for the gpu build, on windows the pytorch channel is required
  - pytorch-cpu 1.9.*
  # - pytorch 1.9.*=*cu*
  # - cudatoolkit 11.1.*
  - tensorflow 1.14.*
  - tiktorch

  # dev-only dependencies
  - conda-build
  - mypy
  - pre-commit
  - pytest >=3,<4
  - pytest-qt

  # ensure working environment on apple M1 via rosetta
  # remove once native builds are available
  - mkl 2021.*  # [osx]
