channels:
  - pytorch
#  - nvidia  # uncomment for pytorch with cuda
  - ilastik-forge
  - conda-forge
  - nodefaults
dependencies:
  - python 3.9.*
  - numpy 1.22.*
  - appdirs
  - cachetools
  - dpct
  - fastfilters
  - future
  - greenlet
  - grpcio 1.41.*
  - h5py
  - hytra
  - ilastik-feature-selection
  - ilastikrag >=0.1.4
  - ilastiktools
  - jsonschema
  - mamutexport
  - marching_cubes
  - ndstructs
  - nifty
  - pandas
  - psutil
  - pydantic 2.*
  - pyopengl
  - pyqt 5.15.*
  - pyqtgraph
  # previous versions would set thread limits globally with side effects
  - python-elf >= 0.4.8
  - qimage2ndarray
  - scikit-image
  - scikit-learn
  # for python 3.7 compatible environment use
  # tiffile >2020.9.22,<=2021.11.2
  - tifffile
  # build 1.11.1=*_1028 on cf is the first to be compatible with numpy>1.19
  # need to bump this manually until there is a true version bump in vigra
  - vigra 1.11.1=*_1033
  # xarray versions not compatible with numpy 1.21, 2023.08.0 might be, but lost trust
  # 2023.10.1 correctly pins numpy to 1.22 and up
  - xarray !=2023.8.0,!=2023.9.0,!=2023.10.0
  - z5py
  - zarr 2.*
  - aiohttp
  - fsspec

  # Neural Network Workflow dependencies
  # can be changed to request gpu versions
  # pytorch 2.4.* will work for all platforms except osx-64, where currently the
  # latest version is 2.2.2
  - pytorch 2.4.*,!=2.4.1
  - cpuonly  # comment out for pytorch with cuda
  # mamba does not "respect" track_features, which is the idea behind cpuonly,
  # with ilastik-pytorch-version-helper-cpu we help mamba on linux and windows
  # to install a cpu-build
  - ilastik-pytorch-version-helper-cpu  # comment out for pytorch with cuda
  # - pytorch-cuda=11.3  # uncomment for pytorch with cuda, specify cuda version

  - tiktorch 24.9.0*


  # Third-party object feature plugins
  - sphericaltexture_plugin
  - sphericaltexture >=0.0.4
  # pyshtools 4.10 conflicts with pytorch (via openmp) on windows
  - pyshtools >=4.12

  # dev-only dependencies
  - conda-build
  - mypy
  - pre-commit
  - pytest >4
  - pytest-qt

  # ensure working environment on apple M1 via rosetta
  # remove once native builds are available
  # - mkl 2021.*  # [osx]

  # must be commented out on arm-64 native (no mkl!)
  - mkl <2024.1.0  # [linux] until pytorch is compatible with the current version
