version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  checkout_ilastik:
    working_directory: /root/ilastik/ilastik
    parallelism: 1
    shell: /bin/bash --login
    environment:
      ILASTIK_ROOT: /root/ilastik
    docker:
    - image: continuumio/miniconda3
    steps:
    - checkout
    - run:
        name: initialize ilastik-meta, link to code
        command: >
            git clone https://github.com/ilastik/ilastik-meta ${ILASTIK_ROOT}/ilastik-meta &&
            cd ${ILASTIK_ROOT}/ilastik-meta &&
            git submodule init &&
            git submodule update --recursive &&
            git submodule foreach "git checkout master" &&
            rm -rf ${ILASTIK_ROOT}/ilastik-meta/ilastik &&
            ln -s ${ILASTIK_ROOT}/ilastik ${ILASTIK_ROOT}/ilastik-meta/ilastik
    - save_cache:
        name: store repo cache
        key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
        paths:
        - /root/ilastik

  test:
    working_directory: /root/ilastik/ilastik
    parallelism: 1
    shell: /bin/bash --login
    environment:
      ILASTIK_ROOT: /root/ilastik
      ON_CIRCLE_CI: 1
      TEST_ENV_NAME: test-env
      VOLUMINA_SHOW_3D_WIDGET: 0
    docker:
    - image: continuumio/miniconda3
    steps:
    - restore_cache:
        name: restoring dependency cache
        keys:
        # This branch if available
        - v1.4.11-dep-{{ .Branch }}-{{ epoch }}
        # Default branch if not
        - v1.4.11-dep-master-
        # Any branch if there are none on the default branch - this should be unnecessary if you have your default branch configured correctly
        - v1.4.11-dep-
    - restore_cache:
        name: restore ilastik-repo cache
        key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
    - run:
        name: update conda
        command: >
            conda config --set always_yes yes --set changeps1 no --set channel_priority strict &&
            conda update -q conda -c conda-forge -c defaults &&
            conda install -n base -c conda-forge -c defaults conda-build
    - run:
        name: install apt dependencies
        command: >
            apt-get update &&
            apt-get install -yy libgl1-mesa-dev xvfb
    - run:
        name: create ilastik conda environment
        command: >
            cd ${ILASTIK_ROOT}/ilastik-meta &&
            python ilastik/scripts/devenv.py create -n ${TEST_ENV_NAME}
            -p ilastik-dependencies-no-solvers mpi4py pytest-cov
            -c ilastik-forge conda-forge defaults
    - run:
        name: run ilastik tests
        command: >
            conda activate ${TEST_ENV_NAME} &&
            cd ${ILASTIK_ROOT}/ilastik-meta/ilastik &&
            mkdir test-results &&
            xvfb-run --server-args="-screen 0 1024x768x24" pytest --cov-report=xml --cov=lazyflow --cov=ilastik --run-legacy-gui --junitxml=test-results/junit.xml
    - store_test_results:
        path: test-results
    - codecov/upload:
        file: coverage.xml
    - save_cache:
        name: store dependency cache
        key: v1.4.11-dep-{{ .Branch }}-{{ epoch }}
        paths:
        - /opt/conda/pkgs

  black:
    working_directory: /root/ilastik/ilastik
    parallelism: 1
    shell: /bin/bash --login
    docker:
    - image: continuumio/miniconda3
    steps:
    - restore_cache:
        name: restore ilastik-repo cache
        key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
    - restore_cache:
        name: restore dependency cache
        keys:
        - v1.4.11-dep-{{ .Branch }}-{{ epoch }}
        - v1.4.11-dep-master-
        - v1.4.11-dep-
    - run:
        name: update conda
        command: >
            conda config --set always_yes yes --set changeps1 no --set channel_priority strict &&
            conda update -q conda -c conda-forge -c defaults
    - run:
        name: create conda environment
        command: >
            conda create -y -n black -c conda-forge -c base black
    - run:
        name: black check
        command: >
            conda activate black &&
            git diff --name-only --diff-filter=AM origin/master.. |
                grep ".*\.py" |
                xargs black --check --line-length=120


workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout_ilastik
      - test:
          requires:
            - checkout_ilastik
      - black:
          requires:
            - checkout_ilastik

