import logging
logger = logging.getLogger(__name__)

from conservationTrackingWorkflow import ConservationTrackingWorkflowFromPrediction, ConservationTrackingWorkflowFromBinary
from animalConservationTrackingWorkflow import AnimalConservationTrackingWorkflowFromPrediction, AnimalConservationTrackingWorkflowFromBinary
