{% set setup_py_data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}

package:
  name: ilastik-package-meta-recipe
  version: {{ setup_py_data.version }}

source:
  path: ..


outputs:
  - name: ilastik-core

    build:
      number: 0
      noarch: python
      script_env:
        - SETUPTOOLS_SCM_PRETEND_VERSION={{ setup_py_data.version }}
      script:
        - python -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    requirements:
      host:
        - python >=3.9
        - pip
        - setuptools >=40.0
        - setuptools_scm
      run:
        - python >=3.9
        - numpy >1.12,<1.27
        # aiohttp to enable zarr.storage.FSStore
        - aiohttp
        - appdirs
        - cachetools
        - certifi
        - dpct
        - fastfilters
        # fsspec to enable zarr.storage.FSStore
        - fsspec
        - future
        - greenlet
        - grpcio !=1.42.*
        - h5py
        - hytra >=1.1.5
        - ilastik-feature-selection
        - ilastikrag >=0.1.4
        - ilastiktools
        - jsonschema
        - mamutexport
        - marching_cubes
        - ndstructs
        - nifty
        - pandas 2.*
        - psutil
        - pydantic 2.*
        - pyopengl
        - pyqt 5.15.*
        # previous versions would set thread limits globally with side effects
        - python-elf >=0.4.8
        # s3fs allows zarr.storage.FSStore to read s3:// URIs
        - s3fs >=2022.8.2
        - scikit-image
        - scikit-learn
        - tifffile >=2022
        # build 1.11.1=*_1028 on cf is the first to be compatible with numpy>1.19
        # need to bump this manually until there is a true version bump in vigra
        - vigra 1.12.1
        - xarray !=2023.8.0,!=2023.9.0,!=2023.10.0
        - z5py
        - zarr 2.*
      run_constrained:
        - tiktorch 25.4.0
        - volumina >=1.3.10
        # TODO: sphericaltexture 0.1.1 currently times out in the tests
        - sphericaltexture 0.0.4
        # pyshtools 4.10 conflicts with pytorch via openmp on windows
        - pyshtools >=4.12

    test:
      imports:
        - ilastik
        - ilastik.experimental
        - ilastik.config
        - ilastik.applets
        - ilastik.workflows
        - lazyflow

      source_files:
        - ilastik
        - lazyflow
        - tests
        - pytest.ini

      requires:
        - python 3.11
        - pytest >4
        - pytest-qt
        - volumina
        - tiktorch

      commands:
        - pytest -v

    about:
      home: https://github.com/ilastik/ilastik
      license: LGPL-2.1-or-later
      summary: >
        ilastik-core package enables ilastik-api usage to mix into environments.
        ilastik is a simple, user-friendly tool for interactive image classification,
        segmentation and analysis.


  - name: ilastik
    build:
      noarch: python
      entry_points:
        - ilastik = ilastik_scripts.ilastik_startup:main
    requirements:
      run:
        - python 3.11.*
        - {{ pin_subpackage("ilastik-core", exact=True) }}
        - pytorch >=2
        - tiktorch
        - torchvision
        - volumina
        # Third-party object feature plugins
        - sphericaltexture_plugin

    test:
      source_files:
        - ilastik
        - lazyflow
        - tests
        - pytest.ini

      requires:
        - pytest >4
        - pytest-qt
        - pytorch 2.*

      imports:
        - ilastik
        - ilastik.experimental
        - ilastik.config
        - ilastik.applets
        - ilastik.workflows
        - lazyflow
        - tiktorch

      commands:
        - ilastik --help
        - pytest -v

    about:
      home: https://github.com/ilastik/ilastik
      license: LGPL-2.1-or-later
      summary: >
        ilastik conda package to create ilastik gui environments.
        ilastik is a simple, user-friendly tool for interactive image classification,
        segmentation and analysis.


  - name: ilastik-gpu
    build:
      noarch: python
      entry_points:
        - ilastik = ilastik_scripts.ilastik_startup:main
    requirements:
      run:
        - python 3.11.*
        - {{ pin_subpackage("ilastik-core", exact=True) }}
        - pytorch >=2
        - pytorch *=*cuda*
        - tiktorch
        - torchvision
        - volumina
        # Third-party object feature plugins
        - sphericaltexture_plugin

    test:
      source_files:
        - ilastik
        - lazyflow
        - tests
        - pytest.ini

      requires:
        - pytest >4
        - pytest-qt
        - pytorch 2.*

      imports:
        - ilastik
        - ilastik.experimental
        - ilastik.config
        - ilastik.applets
        - ilastik.workflows
        - lazyflow
        - tiktorch
        - torch
        - vigra

      commands:
        - ilastik --help
        - pytest -v

    about:
      home: https://github.com/ilastik/ilastik
      license: LGPL-2.1-or-later
      summary: >
        ilastik conda package to create ilastik gpu-enabled gui environments.
        ilastik is a simple, user-friendly tool for interactive image classification,
        segmentation and analysis.
