{% set setup_py_data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}

package:
  name: ilastik-package-meta-recipe
  version: {{ setup_py_data.version }}

source:
  path: ..


outputs:
  - name: ilastik-core

    build:
      number: 0
      noarch: python
      script_env:
        - SETUPTOOLS_SCM_PRETEND_VERSION={{ setup_py_data.version }}
      script:
        - python -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    requirements:
      host:
        - python >=3.7
        - pip
        - setuptools >=40.0
        - setuptools_scm
      run:
        - python >=3.7
        - numpy >1.12
        - appdirs
        - cachetools
        - dpct
        - fastfilters
        - future
        - greenlet
        - grpcio <1.42
        - h5py
        - hytra >=1.1.5
        - ilastik-feature-selection
        - ilastikrag >=0.1.4
        - ilastiktools
        - jsonschema
        - mamutexport
        - marching_cubes
        - ndstructs
        - nifty
        # need to update our packages to be compatible with pandas 2 API
        - pandas
        - psutil
        - pyopengl
        - pyqt 5.15.*
        # previous versions would set thread limits globally with side effects
        - python-elf >=0.4.8
        - scikit-image
        - scikit-learn
        - tifffile >=2023
        # build 1.11.1=*_1028 on cf is the first to be compatible with numpy>1.19
        # need to bump this manually until there is a true version bump in vigra
        - vigra 1.11.2*
        - xarray !=2023.8.0,!=2023.9.0,!=2023.10.0
        - z5py
      run_constrained:
        - tiktorch >=23.11.0
        - volumina >=1.3.10

    test:
      imports:
        - ilastik
        - ilastik.experimental
        - ilastik.config
        - ilastik.applets
        - ilastik.workflows
        - lazyflow

      source_files:
        - tests
        - pytest.ini

      requires:
        - pytest >4
        - pytest-qt
        - volumina
        - tiktorch

      commands:
        - pytest -v .

    about:
      home: https://github.com/ilastik/ilastik
      license: LGPL-2.1-or-later
      summary: >
        ilastik-core package enables ilastik-api usage to mix into environments.
        ilastik is a simple, user-friendly tool for interactive image classification,
        segmentation and analysis.
        

  - name: ilastik
    build:
      noarch: python
      entry_points:
        - ilastik = ilastik_scripts.ilastik_startup:main
    requirements:
      run:
        - python 3.9.*
        - ilastik-core {{ setup_py_data.version }}
        - pytorch >=1.6
        - tiktorch 23.11.0*
        - inferno
        - torchvision
        - volumina

    test:
      source_files:
        - tests
        - pytest.ini

      requires:
        - pytest >4
        - pytest-qt
        # need to help mamba here a bit
        - ilastik-pytorch-version-helper-cpu
        - pytorch 1.13.*

      imports:
        - ilastik
        - ilastik.experimental
        - ilastik.config
        - ilastik.applets
        - ilastik.workflows
        - lazyflow
        - tiktorch

      commands:
        - ilastik --help
        - pytest -v .

    about:
      home: https://github.com/ilastik/ilastik
      license: LGPL-2.1-or-later
      summary: >
        ilastik conda package to create ilastik gui environments.
        ilastik is a simple, user-friendly tool for interactive image classification,
        segmentation and analysis.


  - name: ilastik-gpu
    build:
      noarch: python
      entry_points:
        - ilastik = ilastik_scripts.ilastik_startup:main
    requirements:
      run:
        - python 3.9.*
        - ilastik-core {{ setup_py_data.version }}
        - pytorch >=2
        - tiktorch 23.11.0*
        - inferno
        - torchvision
        - cudatoolkit >=10.2
        - volumina

    test:
      source_files:
        - tests
        - pytest.ini

      requires:
        - pytest >4
        - pytest-qt
        - pytorch 1.13.*
        - cudatoolkit 11.*

      imports:
        - ilastik
        - ilastik.experimental
        - ilastik.config
        - ilastik.applets
        - ilastik.workflows
        - lazyflow
        - tiktorch
        - torch
        - vigra

      commands:
        - ilastik --help
        - pytest -v .

    about:
      home: https://github.com/ilastik/ilastik
      license: LGPL-2.1-or-later
      summary: >
        ilastik conda package to create ilastik gpu-enabled gui environments.
        ilastik is a simple, user-friendly tool for interactive image classification,
        segmentation and analysis.
