{% set setup_py_data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}

package:
  name: ilastik-package-meta-recipe
  version: {{ setup_py_data.version }}

source:
  path: ..


outputs:
  - name: ilastik-core

    build:
      number: 0
      noarch: python
      script_env:
        - SETUPTOOLS_SCM_PRETEND_VERSION={{ setup_py_data.version }}
      script:
        - python -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    requirements:
      host:
        - python >=3.7
        - pip
        - setuptools >=40.0
        - setuptools_scm
      run:
        - python >=3.7
        - numpy >1.12
        - appdirs
        - cachetools
        - dpct
        - fastfilters
        - future
        - greenlet
        - grpcio
        - h5py
        - hytra
        - ilastik-feature-selection
        - ilastikrag
        - ilastiktools
        - jsonschema
        - mamutexport
        - marching_cubes
        - ndstructs
        - nifty
        - psutil
        - pyopengl
        - pyqt 5.12.*
        - python-elf
        - pytiff
        - scikit-image
        - scikit-learn
        # last py37 compatible version
        # newer packages on CF currently don't reflect that
        - tifffile <=2021.11.2
        # build 1.11.1=*_1028 on cf is the first to be compatible with numpy>1.19
        # need to bump this manually until there is a true version bump in vigra
        - vigra 1.11.1=*_1032
        - wsdt
        - xarray
        - z5py
      run_constrained:
        - tiktorch >=22.7.1
        - volumina >=1.3.4

    test:
      imports:
        - ilastik
        - ilastik.experimental
        - ilastik.config
        - ilastik.applets
        - ilastik.workflows
        - lazyflow

      source_files:
        - tests
        - pytest.ini

      requires:
        - pytest >=3,<4
        - pytest-qt
        - volumina
        - tiktorch

      commands:
        - pytest -v .

    about:
      home: https://github.com/ilastik/ilastik
      license: LGPL-2.1-or-later
      summary: >
        ilastik-core package enables ilastik-api usage to mix into environments.
        ilastik is a simple, user-friendly tool for interactive image classification,
        segmentation and analysis.
        

  - name: ilastik
    build:
      noarch: python
      entry_points:
        - ilastik = ilastik_scripts.ilastik_startup:main
    requirements:
      run:
        - python 3.7.*
        - ilastik-core {{ setup_py_data.version }}
        - volumina >=1.3.3
        - pytorch >=1.6
        - tensorflow 1.14.*
        - tiktorch 22.7.1*
        - cpuonly
        - inferno
        - torchvision
    test:
      source_files:
        - tests
        - pytest.ini

      requires:
        - pytest >=3,<4
        - pytest-qt
        # need to help mamba here a bit
        - ilastik-pytorch-version-helper-cpu

      imports:
        - ilastik
        - ilastik.experimental
        - ilastik.config
        - ilastik.applets
        - ilastik.workflows
        - lazyflow
        - tiktorch

      commands:
        - ilastik --help
        - pytest -v .

    about:
      home: https://github.com/ilastik/ilastik
      license: LGPL-2.1-or-later
      summary: >
        ilastik conda package to create ilastik gui environments.
        ilastik is a simple, user-friendly tool for interactive image classification,
        segmentation and analysis.


  - name: ilastik-gpu
    build:
      noarch: python
      entry_points:
        - ilastik = ilastik_scripts.ilastik_startup:main
    requirements:
      run:
        - python 3.7.*
        - ilastik-core {{ setup_py_data.version }}
        - volumina >=1.3.3
        - pytorch >=1.6
        - tensorflow 1.14.*
        - tiktorch 22.7.1*
        - inferno
        - torchvision
        - cudatoolkit >=10.2

    test:
      source_files:
        - tests
        - pytest.ini

      requires:
        - pytest >=3,<4
        - pytest-qt
        - pytorch 1.9.*
        - cudatoolkit 11.1.*

      imports:
        - ilastik
        - ilastik.experimental
        - ilastik.config
        - ilastik.applets
        - ilastik.workflows
        - lazyflow
        - tiktorch
        - torch
        - vigra
        - tensorflow

      commands:
        - ilastik --help
        - pytest -v .

    about:
      home: https://github.com/ilastik/ilastik
      license: LGPL-2.1-or-later
      summary: >
        ilastik conda package to create ilastik gpu-enabled gui environments.
        ilastik is a simple, user-friendly tool for interactive image classification,
        segmentation and analysis.
