from synapsePixelClassificationWorkflow import SynapsePixelClassificationWorkflow
from synapseObjectClassificationWorkflow import SynapseObjectClassificationWorkflow
from synapseBlockwiseWorkflow import SynapseBlockwiseWorkflow
