name: test-test

on:
  workflow_run:
    workflows: [test]
    types: [completed]

jobs:
  test-w-conda-recipe:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: true
          activate-environment: ""
      - uses: actions/cache@v2
        with:
          path: ~/ilastik-pkg
          key: pkg-${{ github.sha }}
      - name: install xvfb/deps
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -yy libgl1-mesa-dev xvfb curl
      - name: install common conda dependencies
        run: conda install -n base -c conda-forge mamba boa setuptools_scm -y
      - name: linux conda build test
        if: matrix.os == 'ubuntu-latest'
        shell: bash -l {0}
        run: |
          LASTIK_PKG=`<~/ilastik-pkg/ilastik-version.txt`
          xvfb-run conda condabuild -c ilastik-forge -c conda-forge conda-recipe --test ~/ilastik-pkg/${ILASTIK_PKG}
      - name: osx conda build test
        if: matrix.os == 'macos-latest'
        shell: bash -l {0}
        run: |
          ILASTIK_PKG=`<~/ilastik-pkg/ilastik-version.txt`
          conda mambabuild -c ilastik-forge -c conda-forge conda-recipe --test ~/ilastik-pkg/${ILASTIK_PKG}
      - name: windows conda-build test
        if: matrix.os == 'windows-latest'
        shell: cmd /C CALL {0}
        # auto activation of env does not seem to work on win
        run: |
          set /p ILASTIK_PKG<%HOME%\ilastik-pkg\ilastik-version.txt
          conda mambabuild -c ilastik-forge -c conda-forge conda-recipe --test < %HOME%\ilastik-pkg\%ILASTIK_PKG
