name: static-code-analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - uses: akaihola/darker@1.7.2
        with:
          options: "--check --diff --revision=origin/main..."
          src: "."
          version: "1.6.0"
