name: test-releases

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-w-conda-recipe:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        ILASTIK_RELEASE_VARIANT: ["", "-gpu"]
        exclude:
          - os: macos-latest
            ILASTIK_RELEASE_VARIANT: "-gpu"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: true
          activate-environment: ""
          miniforge-variant: Mambaforge
          use-mamba: true
      - name: install xvfb/deps
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -yy libgl1-mesa-dev xvfb curl
      - name: install common conda dependencies
        run: mamba install -n base -c conda-forge mamba boa setuptools_scm -y
      - name: linux conda build test
        if: matrix.os == 'ubuntu-latest'
        shell: bash -l {0}
        run: xvfb-run conda mambabuild -c pytorch -c ilastik-forge -c conda-forge conda-recipe
      - name: osx conda build test
        env:
          VOLUMINA_SHOW_3D_WIDGET: 0
        if: matrix.os == 'macos-latest'
        shell: bash -l {0}
        run: conda mambabuild -c pytorch -c ilastik-forge -c conda-forge conda-recipe
      - name: windows conda-build test
        if: matrix.os == 'windows-latest'
        shell: cmd /C CALL {0}
        # auto activation of env does not seem to work on win
        run: conda mambabuild -c pytorch -c ilastik-forge -c conda-forge conda-recipe
